/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SatyaRouteImport } from './routes/satya'
import { Route as SasaRouteImport } from './routes/sasa'
import { Route as RaraRouteImport } from './routes/rara'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as PanduRouteImport } from './routes/pandu'
import { Route as IndexRouteImport } from './routes/index'

const SatyaRoute = SatyaRouteImport.update({
  id: '/satya',
  path: '/satya',
  getParentRoute: () => rootRouteImport,
} as any)
const SasaRoute = SasaRouteImport.update({
  id: '/sasa',
  path: '/sasa',
  getParentRoute: () => rootRouteImport,
} as any)
const RaraRoute = RaraRouteImport.update({
  id: '/rara',
  path: '/rara',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduRoute = PanduRouteImport.update({
  id: '/pandu',
  path: '/pandu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pandu': typeof PanduRoute
  '/player': typeof PlayerRoute
  '/rara': typeof RaraRoute
  '/sasa': typeof SasaRoute
  '/satya': typeof SatyaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pandu': typeof PanduRoute
  '/player': typeof PlayerRoute
  '/rara': typeof RaraRoute
  '/sasa': typeof SasaRoute
  '/satya': typeof SatyaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pandu': typeof PanduRoute
  '/player': typeof PlayerRoute
  '/rara': typeof RaraRoute
  '/sasa': typeof SasaRoute
  '/satya': typeof SatyaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pandu' | '/player' | '/rara' | '/sasa' | '/satya'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pandu' | '/player' | '/rara' | '/sasa' | '/satya'
  id: '__root__' | '/' | '/pandu' | '/player' | '/rara' | '/sasa' | '/satya'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanduRoute: typeof PanduRoute
  PlayerRoute: typeof PlayerRoute
  RaraRoute: typeof RaraRoute
  SasaRoute: typeof SasaRoute
  SatyaRoute: typeof SatyaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/satya': {
      id: '/satya'
      path: '/satya'
      fullPath: '/satya'
      preLoaderRoute: typeof SatyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sasa': {
      id: '/sasa'
      path: '/sasa'
      fullPath: '/sasa'
      preLoaderRoute: typeof SasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rara': {
      id: '/rara'
      path: '/rara'
      fullPath: '/rara'
      preLoaderRoute: typeof RaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pandu': {
      id: '/pandu'
      path: '/pandu'
      fullPath: '/pandu'
      preLoaderRoute: typeof PanduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanduRoute: PanduRoute,
  PlayerRoute: PlayerRoute,
  RaraRoute: RaraRoute,
  SasaRoute: SasaRoute,
  SatyaRoute: SatyaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
